### ISSUE TITLE
Variable-sized panels

### ISSUE THREAD

**Issue by huyl** [jmar777/kwicks#2]
Would love to see that, as mentioned in http://stackoverflow.com/a/12784159/161972

**Comment by Duke3D** [comment]
Request is still unclear to me.  
For a horizontal panel, I would expect all images to have the same image height matching (or if responsive, in proportiion to) the panel height.
If the request is to use images of different aspect ratios - different expanded widths - then is the intention that the collapsed images all reduce to the same reduced width, which changes and is the same width for all collapsed images depending on the width of the currently expanded image,, or that each image reduces in proportion to it's expanded size?

First case example:
5 images in default state.  Each displays equal-width in a window that is 20% of the container width.
When one is expanded, it is expanded to it's full width and all others are displayed narrower but with equal widths.
e.g. The currently expanded image happens to be 60% of the container (600 pixels wide in a 1000 pixel container) and four remaining images are displayed in equal-size, 10% wide windows.  
These display as 100px (10%), 100px (10%), 100px (10%), 600px (60%), 100px (10%) = 1000 px / 100%

The next expanded image happens to be 40% of the container and four remaining images are displayed in equal-size, 15% wide windows.  
These display as 150px (15%), 400px (40%), 150px (15%), 150px (15%), 150px (15%) = 1000 px / 100%

Second case example:
5 images in default state.  Each displays in a proportionately-sized window.
Assume images that are 300px, 400px, 300px, 600px, 400px. and container is 1000px.
these would display as 150px (15%), 200px (20%), 150px (15%), 300px (30%), 200px (20%) = 1000 px / 100%

When one is expanded, it is expanded to it's full width and all others are displayed narrower in proportion to their widths.
e.g. The currently expanded image is panel no. 2 (400px) which happens to take 40% of the container so the four remaining images are displayed in windows that make up the remaining 60%.  These would display as:
112px (11.25%), 400px (40%), 112px (11.25%), 225px (22.5%), 150px (15%) = 999px / 100%

The next expanded image happens to be panel 4 which happens to take 60% of the container so the four remaining images are displayed in proportionately smaller windows that make up the remaining 40%.  These would display as:  86px (8.58%), 114px (11.42%), 86px (8.58%), 600px (60%), 114px (11.42%) = 1000px / 100%

Aesthetically, the reduced-width images suggesting the width of their fully expanded content is not as important as the visual symmetry of all reduced size slices being equal width.  Unless there is a good use case for it, my preference would be the first example - the code reads the actual dimension of the image and computes remaining windows equally.  In a responsive version, the minSize value would be used to force a minimum slice size, say 8% and the expanded window reduces to preserve that minimum - e.g. width = actual pixel width of image, max-width 68% of container (100% - 4 panels @ 8%)  A fully responsive version would also scale the images to maintain the aspect ratio of the container.  If when designed for 1000 pixels, the best height is 200 px, then set container height to 20%, max-width to 100%, and scale panels and images to fit that height.

**Comment by Duke3D** [comment]
EDIT - Just recreated the OP's final Fiddle - It doesn't seem to match the intent of Kwicks - his CSS solution is a better fit.  I suggest Closing this misleading request though the related idea for use with images might have merit as interpreted below...

Jeremy - Since the OP has not responded, I would interpret this request as one to compute max-size as the entered parameter or the actual dimension of the selected image, whichever is lower.  This prevents excessive gaps or stretching an image to larger than actual pixels.   It also means both the sizes and offsets for expanded are recalculated per image instead of just panel-wide - either a 2D array that is cached in memory or more overhead/computing with each event.

If simplified as described, I see this enhancement as a more robust version of responsive when the source images are unequal in size, but I'm not sure there is a significant use case beyond doing an automated image selector for a dynamic photo gallery that has both landscape and portrait images.  A good idea, but seemingly limited value.  Is it worth the effort?

**Comment by jmar777** [comment]
I can imagine something like this being useful... especially with horizontal menus (which a lot of people have used Kwicks for).  E.g.,

`home | products | blog | about us | contact`

Each menu link of course has it's own width, and it may be useful to allow a "kwicks-like" effect without forcing the same dimensions on them.  I think your question at the end is appropriate, though ("is it worth the effort?").  Definitely not Kwicks' primary use case, and there's a lot of subtle issues around dynamically calculating the dimensions of the panels.  Perhaps simply allowing arrays to be passed for `maxSize` and `minSize` would do the trick... sort of creates an implicit contract that it's not meant for dynamically resized panel contents.  Personally I'm on the fence about it... don't want to add it just yet, but not ruling it out either.  If there were more requests for this, it would sway me.  The implementation itself shouldn't be too bad, but in general the leaner we can keep the API, the better.

**Comment by Duke3D** [comment]
My production use is as a menu with an overlaying text that rotates 90 on expand and a drop-down menu below.

Aesthetically, I think I would always choose to have the image slices equally-sized as opposed to directed by the width of the text simply because the image shape is far more dominant visually than the usually much smaller text shape.  I would think other designers setting up a menus would opt to have equal size/aspect ratio images to look harmonious rather than opt for varied sized that suggest the animation is misaligned/broken.  So, I agree with the conclusion.  I don't think this is complex enough to make the slightly larger file size a factor.  

I am still liking the idea of computing max-size as the entered parameter or the actual dimension of the selected image, whichever is lower just so the panel won't appear overstretched (meaning needlessly larger spacing gaps instead or more image revealed for the non-expanded images) when displayed responsively on a larger screen, but this minor fix can be accomplished without computing per-image sizing for unequally sized images.  Beyond this, I really like the simple API for responsive and would hate to muck it up.  Simple elegance.

**Comment by jmar777** [comment]
It's been 9 months since we've heard from the OP, and I'm still not sure I grok or agree with the idea, so closing for now.  Feel free to re-open if you have any clarification on the request.
