### ISSUE TITLE
dynamic add <li> case something strange.

### ISSUE THREAD

**Issue by guoxiangyang** [jmar777/kwicks#20]
Hi,
   I'm trying dynamic add new panel.
   After new <li> added, use e.kwicks() to reinitialization the panel, it works.
   the problem is : if reinit with e.kwicks({behavior:"menu"}), the onSelect event handle seem remount each time. 
   So, if I add 2 new panel, the old panel click will trigger onSelect() 3 times. the first new panel will trigger onSelect() 2 times. the last panel trigger 1 time.
  I think the initialization process has something wrong.

**Comment by jmar777** [comment]
Hey, sorry for the delay - somehow I keep missing these issues.  Right now the behavior you're seeing is what would be expected... it's not really designed to allow for dynamically adding/removing panels (although that could be considered in the future).  However, the next version will include a `.kwicks('destroy')` method that will allow you to tear down any existing event handlers, so that when you re-initialize you won't end up with redundant events being fired.

**Comment by jmar777** [comment]
Alright, v2.2.0 is out with a lot of updates, including a `.kwicks('destroy')` event.  You can now call this before adding/removing panels, and then re-initialize the kwicks plugin.  The [home page](http://devsmash.com/projects/kwicks) has a rundown of everything that's new/changed.
