### ISSUE TITLE
Incorporate Image rotate in one of the slides

### ISSUE THREAD

**Issue by sonamlucky** [jmar777/kwicks#40]
Hi, I have been using the kwicks slider and i like the simplicity.
I have setup up a slider with 4 images horizontal.
First i would like to add a few rotating images to the first slide which is always shows as expanded. Is that possible ?
Second the slider loads up with one slide on display and then shows the rest. About 2 second delay. Can it be smoother loading on screen.
Many Thanks
The link for the web is http://camb.ardentlabs.co.uk/

**Comment by sonamlucky** [comment]
hi any help Please ?

**Comment by jmar777** [comment]
Are you saying you want to rotate background images within the first panel?  If so, that should be fairly simple (although it doesn't have anything to do with kwicks itself at that point):

``` javascript
$('.kwicks .backgroundimage:first').css('background-image', 'url("some-image.jpg")');
```

You should be able to just cycle through whatever images you want w/ some `setTimeout`'s.

Regarding the jerkiness when the slider is loading, you'll want to style the panels with CSS so that they look better before the plugin has had a chance to run.  For example, notice how CSS is being applied to the panels [here](http://devsmash.com/projects/kwicks/2.2.x/examples/horizontal) so that they look correct immediately on page load, even before the plugin has been invoked.

Hope that helps!

**Comment by sonamlucky** [comment]
Thank you i will see how i can implement this into the slider.

**Comment by sonamlucky** [comment]
Hi Again,
I tried this:

window.setInterval(function(){ 
window.setTimeout(function(){

$('.kwicks .backgroundimage:first').css('background-image', 'url("/wp-content/themes/roots/assets/img/slides/s1.jpg")'); },4000);

$('.kwicks .backgroundimage:first').css('background-image', 'url("/wp-content/themes/roots/assets/img/slides/s2.jpg")'); },4000);

It works for these images, but i cant seem to add any more slides as it doesnt work. 
Im just getting my head around this. Learning along the way. Appreciate any help. Thanks

**Comment by sonamlucky** [comment]
HI i managed to use a simple CSS slide and it worked.
Thanks for your help
