### ISSUE TITLE
Close an expanded panel

### ISSUE THREAD

**Issue by morrisad** [jmar777/kwicks#45]
Hi there. I have a question - I have two navs going on: one is the kwicks and the other is a top nav bar. If I choose a kwicks panel, it expands and shows me the content of my hidden div below. So far so good. If I now click a link on the top nav bar hiding this div and showing another section, the expanded panel on the Kwicks remains open despite the new section being now open below it...  Is there a way to collapse open panels on the Kwicks menu when links elsewhere are clicked?

**Comment by jmar777** [comment]
Hey, sorry for the delayed response on this.  You can collapse all panels on a Kwicks instance by using `$('#the-element').kwicks('expand', -1)` (see this [example](http://devsmash.com/projects/kwicks/2.2.x/examples/expand-method)).  Is that what you were looking for?

**Comment by morrisad** [comment]
Hey! Thanks for getting back to me. This looks as though it's the answer I was looking for but I'm not sure how to get it all working. I've tried to attach the data-index='-1' to the top bar links and then include them in the jquery but it's a no go at the mo... the test-site is here: http://www.adammorris/7therapies .If you can see straight away how to include the data-indexes, please put me out of my misery!!

**Comment by morrisad** [comment]
(It's http://www.adammorris.net/7therapies of course....... )

**Comment by jmar777** [comment]
Ahh, the `data-index` stuff was rather one-off for that particular example.  Looking at your code, you probably actually want something like this in your case:

``` javascript
$(function() {
    var $kwicks = $('.kwicks').kwicks({
        maxSize: '50%',
        behavior: 'menu'
    });

    $('header nav a').click(function() {
        $kwicks.kwicks('select', -1);
    });
});
```

Explanation: the `menu` behavior option actually combines the `expand` method (which is what happens when you mouseover) along with `select` method, which is basically just "sticky" expanding, and is what causes the most recently clicked panel to re-expand when the mouse moves outside of the container.  All that being said, then, the solution would really just be to capture click events on your header links, and then reset the currently _selected_ panel (as opposed to the currently _expanded_ one).  Again, they're visually the same thing... "select" just has some statefulness that "expand" doesn't.

Hope that helps!

**Comment by morrisad** [comment]
That's it!!!! Tried to use the code above a few times today but it still wasn't working but I just had another look and noticed that the kwicks.kwicks variable was looking odd in my bbedit, so I changed it to match the one above and... BINGO! Thank you so much for the help, Jeremy! Adam 

$('header nav a').click(function() {
 $('.kwicks').kwicks('select', -1);
   });

**Comment by jmar777** [comment]
Awesome, glad that worked! I'm going to go ahead and close this issue, but feel free to re-open it or file a new one with any further questions!
