### ISSUE TITLE
Newscast Accordion Slider

### ISSUE THREAD

**Issue by tinawexler** [jmar777/kwicks#6]
HELP!  Please!  My website is http://www.tinawexler.com

I love my site, but my slider gets hung up when loading in ie.  I don't want to have to change the site, but I need it to fully function. Please, tell me that you have a fix.  

Tina

**Comment by jmar777** [comment]
Hey Tina - I checked out your site, but I don't see kwicks in use anywhere.  I see that you're using a similar effect on the home page, but I can't find any references to kwicks itself anywhere.

**Comment by tinawexler** [comment]
Well, if it’s similar and can provide the same effect, I’m happy to switch.  Does the kwicks one work with ie… and everyone else?  How hard would it be for a novice to make the switch?

Tina Wexler

847.926.3132

 http://www.tinawexler.com/ Tina Wexler, LLC

Business Development & Marketing Expertise

**Comment by jmar777** [comment]
Browser support is as follows:
- Chrome 12+
- FF 3.6+
- IE7+
- Opera 11+
- Safari 5+

The home page has documentation and links to several examples to help get you started: http://devsmash.com/projects/kwicks

How hard it would be to implement is entirely dependent on how much experience you have with JavaScript/jQuery/CSS/etc.  The library is designed to be straight forward to use though.  It doesn't provide any out of the box spinners/loading behavior like your site currently features, but nothing about Kwicks prevents this from happening at a sub-panel level.

I'm going to go ahead and close this issue since it doesn't seem to indicate a bug with Kwicks itself, but feel free to continue commenting here if you need additional help.
