### ISSUE TITLE
Can Panels Have Borders?

### ISSUE THREAD

**Issue by SteverPalm** [jmar777/kwicks#9]
When I try to put borders around the panels, the spacing between the last two panels is smaller than the rest.
Example: http://www.stephenpalmphotography.com/kwicks/
Is there any way to fix this?
Thanks,
StevePalm

**Comment by jmar777** [comment]
Hey Steve - 

At the moment there's not a super elegant way of doing that, since the border actually adds to the width of the panels.  I'll look into the possibility of having kwicks check for the existence of a border when it's figuring out positioning.

Here's a workaround that I believe will work for you, though.  Basically, just leave the border off of the actual kwicks panel, so the widths/offsets are calculated correctly, and then add the border to a nested element.  You'll want to set the `width` to `auto` and the `height` to `panelHeight - (borderWidth * 2)`.  Here's an example if that's not clear (note the styling on the `.panel` elements: http://jsfiddle.net/wwLUZ/1/

Hope that helps,
- Jeremy

**Comment by SteverPalm** [comment]
Thanks for the quick response and the
workaround Jeremy. I'm sure I can get it to work. BTW nice job on the
sliding panels. They work awesome. I found the kwicks site a while
back and have been trying to think of a good way to implement them
into one of my websites. Then one day a friend of mine was
complaining about the look and functionality of his menus for his
guitar website. That gave me the opportunity to build something with
the sliding panels and he thinks his menus looks awesome now.

Have a good one,
SteveDate: Tue, 29 Jan 2013 06:29:14 -0800

**Comment by jmar777** [comment]
Awesome, Steve. Glad it was helpful and that your buddy likes the new look!  I'm going to go ahead and close out this issue, but feel free to reopen or file a new one if you have any more problems.
